### ISSUE TITLE
Possible JavaScript Breakage Between 4.13.0 and 4.14.0

### ISSUE THREAD

**Issue by tntim96** [HtmlUnit/htmlunit#1001]
I am using HTMLUnit 4.13.0 and after upgrading to 4.14.0 I a [test is failing](https://github.com/tntim96/JSCover/actions/runs/16738413704).

You can probably checkout the branch 'html-unit-4.14.0' of JSCover and debug to see what's going on.

The test is HtmlUnitJSTest.shouldTestJavaScript.

I'll see if I can put in some console statements to help resolve this issue. Currently I just get a stack-trace
```
org.htmlunit.ScriptException: Index 2 out of bounds for length 2
	at org.htmlunit.javascript.JavaScriptEngine.handleJavaScriptException(JavaScriptEngine.java:1049)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:947)
	at org.htmlunit.corejs.javascript.Context.call(Context.java:638)
	at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:448)
...
```

**Comment by RuralHunter** [comment]
yeah, I got the similar problem:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at org.htmlunit.corejs.javascript.Interpreter.getArgsArray(Interpreter.java:4824)
	at org.htmlunit.corejs.javascript.Interpreter.access$000(Interpreter.java:24)
	at org.htmlunit.corejs.javascript.Interpreter$CallFrame.initializeArgs(Interpreter.java:256)
	at org.htmlunit.corejs.javascript.Interpreter.initFrame(Interpreter.java:4595)
	at org.htmlunit.corejs.javascript.Interpreter.access$17400(Interpreter.java:24)
	at org.htmlunit.corejs.javascript.Interpreter$DoCallByteCode.execute(Interpreter.java:3402)
	at org.htmlunit.corejs.javascript.Interpreter.interpretFunction(Interpreter.java:1821)
	at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1597)
	at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1221)
	at org.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:108)
	at org.htmlunit.corejs.javascript.Script.exec(Script.java:28)
	at org.htmlunit.javascript.JavaScriptEngine$1.doRun(JavaScriptEngine.java:785)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:933)
```

**Comment by rbri** [comment]
@tntim96 , @RuralHunter sorry for that. 4.14.0 was a major Rhino/core-js update, maybe i made a mistake when merging all that stuff. Will try to extract a test case and hopefully fix that soon.

**Comment by rbri** [comment]
Ok, can reproduce the error with the JScover code. Looks like had stuff - please be a bit patient

**Comment by rbri** [comment]
@tntim96 , @RuralHunter can you please give the 4.15.0-SNAPSHOT a try... hopefully the issue is fixed

**Comment by tntim96** [comment]
Is that SNAPSHOT published? It's not resolving for me ATM.

I have tried a couple of snapshot repos
```
        <repository>
            <id>Sonatype repository</id>
            <name>Sonatype's Maven repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
        <repository>
            <id>Sonatype repository2</id>
            <name>Sonatype's Maven repository</name>
            <url>https://central.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
```

**Comment by tntim96** [comment]
I've built the SNAPSHOT locally from commit [6a33877](https://github.com/HtmlUnit/htmlunit/commit/6a338772a9b47d9d7e3f89dd9967eba8e7761432) and that seems to fix the issue with JSCover's `HtmlUnitJSTest.shouldTestJavaScript` test.

**Comment by RuralHunter** [comment]
@tntim96  Here is the snapshot repo info: https://github.com/HtmlUnit/htmlunit/blob/master/README.md#maven-1

**Comment by RuralHunter** [comment]
I tested 4.15.0-SNAPSHOT and it didn't fix my problem:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at org.htmlunit.corejs.javascript.Interpreter.getArgsArray(Interpreter.java:4849)
	at org.htmlunit.corejs.javascript.Interpreter.access$000(Interpreter.java:24)
	at org.htmlunit.corejs.javascript.Interpreter$CallFrame.initializeArgs(Interpreter.java:256)
	at org.htmlunit.corejs.javascript.Interpreter.initFrame(Interpreter.java:4618)
	at org.htmlunit.corejs.javascript.Interpreter.access$17400(Interpreter.java:24)
	at org.htmlunit.corejs.javascript.Interpreter$DoCallByteCode.execute(Interpreter.java:3416)
	at org.htmlunit.corejs.javascript.Interpreter.interpretFunction(Interpreter.java:1821)
	at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1597)
	at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1221)
	at org.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:108)
	at org.htmlunit.corejs.javascript.Script.exec(Script.java:28)
	at org.htmlunit.javascript.JavaScriptEngine$1.doRun(JavaScriptEngine.java:785)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:933)
```
and another new error:
```
Caused by: org.htmlunit.corejs.javascript.EcmaError: TypeError: "this" is not an instance of class NativeNumber (https://lf-c-flwb.bytetos.com/obj/rc-client-security/web/glue/1.0.0.55/sdk-glue.js#2)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:5686)
	at org.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:5667)
	at org.htmlunit.corejs.javascript.ScriptRuntime.typeError(ScriptRuntime.java:5699)
	at org.htmlunit.corejs.javascript.ScriptRuntime.typeErrorById(ScriptRuntime.java:5704)
	at org.htmlunit.corejs.javascript.LambdaConstructor.convertThisObject(LambdaConstructor.java:448)
	at org.htmlunit.corejs.javascript.NativeNumber.toSelf(NativeNumber.java:193)
	at org.htmlunit.corejs.javascript.NativeNumber.js_toString(NativeNumber.java:202)
	at org.htmlunit.corejs.javascript.Interpreter$DoCallByteCode.execute(Interpreter.java:3466)
	at org.htmlunit.corejs.javascript.Interpreter.interpretFunction(Interpreter.java:1821)
	at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1597)
	at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1221)
	at org.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:108)
	at org.htmlunit.corejs.javascript.Script.exec(Script.java:28)
	at org.htmlunit.javascript.JavaScriptEngine$1.doRun(JavaScriptEngine.java:785)
	at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:933)
```

**Comment by tntim96** [comment]
It worked for JSCover and build is green: https://github.com/tntim96/JSCover/actions/runs/16821191177

**Comment by rbri** [comment]
@RuralHunter any chance to provide the url or even better a test case?

**Comment by rbri** [comment]
fix is now merged into the rhino head and i made a fresh build ob the core-js snapshot

**Comment by rbri** [comment]
@RuralHunter ?

**Comment by RuralHunter** [comment]
@rbri sorry for the delay. I tried to get out a test case and here it is:
```
            function greet(name, age) {
                console.log(`Hello ${name}, you are ${age}. Context:`, this);
            }

            var person = {id: 1};
            // Using call.apply:
            greet.call.apply(greet, [person, "Bob", 40]);
```
It seems func.call.apply causes the error while func.apply works fine.

**Comment by rbri** [comment]
@RuralHunter thanks a lot, will try to get it fixed in Rhino as soon as possible

**Comment by rbri** [comment]
Strange, the code seems to work with plain Rhino but not with core-js.

**Comment by rbri** [comment]
@RuralHunter many many thanks for taking the time to nail down the problem. Was able to make a Rhino issue out of your one, lets cross our fingers...

**Comment by RuralHunter** [comment]
cool, thanks!

**Comment by rbri** [comment]
@RuralHunter can you please try the latest core-js snapshot build from today....

**Comment by RuralHunter** [comment]
Thanks, I can confirm the error is gone!

**Comment by rbri** [comment]
thanks for the fast feedback, will try to make a release this weekend

**Comment by rbri** [comment]
4.15.0 is out - enjoy
